### ISSUE TITLE
Connecting Repo to the Server

### ISSUE THREAD

**Issue by pcversal** [einfiction/esresearchlab#1]
Connecting the repo to **esresearchlab.org** 

After Auto-Deployment is Set Up
Once auto-deployment using webhooks has been setup, any changes committed to the main branch will automatically be deployed to the server.

----

**2. Connect the Repo to Your Server**
To deploy the website, you need to connect your GitHub repository to your server. Here’s a basic outline of how to do it using a server with SSH access:

**Using a Webhook (Automatic Deployment)**
Set Up a Webhook:

Go to your GitHub repository.
Navigate to Settings > Webhooks.
Click Add webhook.
Set the payload URL to your server's URL where a webhook handler will be listening.
Choose application/json as the content type.
Select Just the push event for the events to trigger the webhook.

Create a Webhook Handler on Your Server:

Write a script to handle the webhook and pull changes from the repository.
Example script (deploy.sh):

#!/bin/bash
cd /path/to/your/website
git pull origin main

**3. Set Up a Service to Listen for Webhook Events:**

Use a tool like node.js or python to listen for webhook events and execute your deployment script.
Example using node.js and express:

javascript

const express = require('express');
const { exec } = require('child_process');
const app = express();

app.post('/webhook', (req, res) => {
    exec('sh /path/to/deploy.sh', (error, stdout, stderr) => {
        if (error) {
            console.error(`Error: ${error.message}`);
            return;
        }
        if (stderr) {
            console.error(`Stderr: ${stderr}`);
            return;
        }
        console.log(`Stdout: ${stdout}`);
    });
    res.status(200).send('Webhook received');
});

app.listen(3000, () => console.log('Listening on port 3000'));

**4. Install Dependencies and Run the Service:**

Install dependencies:
bash

npm install express

Run your service:
bash

node your_webhook_service.js

**Comment by maxnag** [comment]
@pcversal 
There is not enough info to handle this action.
- Set the payload URL to your server's URL where a webhook handler will be listening. - What the server URL

**Comment by pcversal** [comment]
@maxnag 
"Set the payload URL to your server's URL where a webhook handler will be listening. - What the server URL"
@BestianCode will take care of this.

**Comment by BestianCode** [comment]
A bit strange description of deployment and how to run it, because there is just a static site, without any nodejs, etc. But deployed. Every commit will be redeployed.
